from app.ai.prompts.identity_operations import (
    IDENTITY_OPERATIONS_INSTRUCTIONS as _BASE_IDENTITY_OPERATIONS_INSTRUCTIONS,
)
from app.ai.prompts.remediation_response_guidance import (
    REMEDIATION_RESPONSE_GUIDANCE,
)


IDENTITY_OPERATIONS_INSTRUCTIONS = (
    _BASE_IDENTITY_OPERATIONS_INSTRUCTIONS
    + REMEDIATION_RESPONSE_GUIDANCE
)

__all__ = [
    "IDENTITY_OPERATIONS_INSTRUCTIONS",
]
