from __future__ import annotations

import json
from concurrent.futures import ThreadPoolExecutor
from uuid import uuid4

import pytest
from sqlalchemy import text
from sqlalchemy.exc import IntegrityError

from app.database.session import IS_POSTGRESQL, engine


pytestmark = pytest.mark.skipif(
    not IS_POSTGRESQL,
    reason="PostgreSQL runtime tests require DATABASE_URL to point to PostgreSQL.",
)


def test_postgresql_connection_and_database_identity() -> None:
    with engine.connect() as connection:
        database_name, user_name = connection.execute(
            text("select current_database(), current_user")
        ).one()

    assert database_name
    assert user_name
    assert engine.dialect.name == "postgresql"


def test_postgresql_jsonb_round_trip() -> None:
    payload = {
        "nested": {"enabled": True},
        "values": [1, 2, 3],
        "label": "IdentityAI",
    }

    with engine.connect() as connection:
        result = connection.execute(
            text("select cast(:payload as jsonb)"),
            {"payload": json.dumps(payload)},
        ).scalar_one()

    assert result == payload


def test_postgresql_foreign_keys_are_enforced() -> None:
    suffix = uuid4().hex
    parent = f"pg_test_parent_{suffix}"
    child = f"pg_test_child_{suffix}"

    with engine.connect() as connection:
        transaction = connection.begin()
        try:
            connection.execute(
                text(f'create table "{parent}" (id integer primary key)')
            )
            connection.execute(
                text(
                    f'create table "{child}" ('
                    f'id integer primary key, '
                    f'parent_id integer not null references "{parent}"(id)'
                    f')'
                )
            )

            with pytest.raises(IntegrityError):
                with connection.begin_nested():
                    connection.execute(
                        text(f'insert into "{child}" (id, parent_id) values (1, 999)')
                    )
        finally:
            transaction.rollback()


def test_postgresql_transaction_rollback_isolation() -> None:
    suffix = uuid4().hex
    table = f"pg_test_rollback_{suffix}"

    with engine.connect() as connection:
        transaction = connection.begin()
        connection.execute(
            text(f'create table "{table}" (id integer primary key, value text not null)')
        )
        connection.execute(
            text(f'insert into "{table}" (id, value) values (1, :value)'),
            {"value": "temporary"},
        )
        assert connection.execute(
            text(f'select count(*) from "{table}"')
        ).scalar_one() == 1
        transaction.rollback()

    with engine.connect() as connection:
        exists = connection.execute(
            text(
                "select to_regclass(:qualified_name)"
            ),
            {"qualified_name": f"public.{table}"},
        ).scalar_one()

    assert exists is None


def test_postgresql_identity_sequence_advances() -> None:
    suffix = uuid4().hex
    table = f"pg_test_sequence_{suffix}"

    with engine.connect() as connection:
        transaction = connection.begin()
        try:
            connection.execute(
                text(
                    f'create table "{table}" ('
                    f'id integer generated by default as identity primary key, '
                    f'value text not null)'
                )
            )
            first_id = connection.execute(
                text(f'insert into "{table}" (value) values (:value) returning id'),
                {"value": "first"},
            ).scalar_one()
            second_id = connection.execute(
                text(f'insert into "{table}" (value) values (:value) returning id'),
                {"value": "second"},
            ).scalar_one()

            assert second_id == first_id + 1
        finally:
            transaction.rollback()


def test_postgresql_pool_supports_concurrent_writes() -> None:
    suffix = uuid4().hex
    table = f"pg_test_concurrent_{suffix}"

    with engine.begin() as connection:
        connection.execute(
            text(
                f'create table "{table}" ('
                f'id integer generated by default as identity primary key, '
                f'worker integer not null)'
            )
        )

    try:
        def insert_worker(worker_id: int) -> None:
            with engine.begin() as connection:
                connection.execute(
                    text(f'insert into "{table}" (worker) values (:worker)'),
                    {"worker": worker_id},
                )

        with ThreadPoolExecutor(max_workers=5) as executor:
            list(executor.map(insert_worker, range(10)))

        with engine.connect() as connection:
            count = connection.execute(
                text(f'select count(*) from "{table}"')
            ).scalar_one()

        assert count == 10
    finally:
        with engine.begin() as connection:
            connection.execute(text(f'drop table if exists "{table}"'))
