import {
  useCallback,
  useMemo,
  useState,
} from "react";

import {
  Alert,
  Box,
  CircularProgress,
  Drawer,
} from "@mui/material";

import ChatHeader from "./ChatHeader";
import ChatInput from "./ChatInput";
import ChatMessages from "./ChatMessages";
import SuggestedPrompts from "./SuggestedPrompts";

import type {
  ChatHistoryMessage,
  ChatMessage,
} from "../../models/chat";

import {
  askAI,
} from "../../services/aiService";

interface Props {
  open: boolean;
  onClose: () => void;
}

function createMessageId(): string {
  return `${Date.now()}-${Math.random()
    .toString(36)
    .slice(2)}`;
}

function createWelcomeMessage(): ChatMessage {
  return {
    id: createMessageId(),
    role: "assistant",
    content:
      "👋 Hello! I'm IdentityAI Copilot.\n\n"
      + "I can help you analyze duplicate accounts, "
      + "explain confidence scores, review scan results, "
      + "and answer IAM-related questions.",
    timestamp: new Date(),
  };
}

const ChatBot = ({
  open,
  onClose,
}: Props) => {
  const [
    messages,
    setMessages,
  ] = useState<ChatMessage[]>(() => [
    createWelcomeMessage(),
  ]);

  const [
    conversationId,
    setConversationId,
  ] = useState<string | null>(null);

  const [
    loading,
    setLoading,
  ] = useState(false);

  const [
    error,
    setError,
  ] = useState("");

  const [
    useReasoningModel,
  ] = useState(false);

  const conversationHistory =
    useMemo<ChatHistoryMessage[]>(() => {
      /*
       * Exclude the initial welcome message because it
       * was generated by the frontend, not by the model.
       */
      return messages
        .slice(1)
        .map((message) => ({
          role: message.role,
          content: message.content,
        }))
        .slice(-30);
    }, [messages]);

  const sendMessage = useCallback(
    async (
      text: string,
    ): Promise<void> => {
      const normalizedText =
        text.trim();

      if (
        !normalizedText
        || loading
      ) {
        return;
      }

      /*
       * Send only messages that existed before the new
       * user message. The backend receives the new text
       * separately through payload.message.
       *
       * This avoids submitting the current user message
       * twice.
       */
      const historyBeforeMessage =
        conversationHistory;

      const userMessage: ChatMessage = {
        id: createMessageId(),
        role: "user",
        content: normalizedText,
        timestamp: new Date(),
      };

      setMessages((previous) => [
        ...previous,
        userMessage,
      ]);

      setLoading(true);
      setError("");

      try {
        const response = await askAI(
          normalizedText,
          historyBeforeMessage,
          conversationId,
          useReasoningModel,
        );

        setConversationId(
          response.conversationId,
        );

        const assistantMessage:
          ChatMessage = {
            id: createMessageId(),
            role: "assistant",
            content:
              response.message
              || "No response was generated.",
            timestamp: new Date(),
          };

        setMessages((previous) => [
          ...previous,
          assistantMessage,
        ]);
      } catch (requestError) {
        console.error(
          "AI assistant request failed:",
          requestError,
        );

        const message =
          requestError instanceof Error
            ? requestError.message
            : (
              "Unable to reach the "
              + "AI assistant."
            );

        setError(message);

        const errorMessage:
          ChatMessage = {
            id: createMessageId(),
            role: "assistant",
            content:
              "I could not complete that request.\n\n"
              + message,
            timestamp: new Date(),
          };

        setMessages((previous) => [
          ...previous,
          errorMessage,
        ]);
      } finally {
        setLoading(false);
      }
    },
    [
      conversationHistory,
      conversationId,
      loading,
      useReasoningModel,
    ],
  );

  return (
    <Drawer
      anchor="right"
      open={open}
      onClose={
        loading
          ? undefined
          : onClose
      }
      slotProps={{
        paper: {
          sx: {
            width: {
              xs: "100%",
              sm: 440,
            },
            maxWidth: "100vw",
            display: "flex",
            flexDirection: "column",
            overflow: "hidden",
          },
        },
      }}
    >
      <ChatHeader />

      <SuggestedPrompts
        onSelect={sendMessage}
      />

      {error && (
        <Alert
          severity="error"
          onClose={() =>
            setError("")
          }
          sx={{
            mx: 2,
            mt: 1,
          }}
        >
          {error}
        </Alert>
      )}

      <ChatMessages
        messages={messages}
      />

      {loading && (
        <Box
          sx={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            gap: 1,
            py: 1.5,
          }}
        >
          <CircularProgress
            size={20}
          />

          <Box
            component="span"
            sx={{
              fontSize: 13,
              color: "text.secondary",
            }}
          >
            IdentityAI is thinking...
          </Box>
        </Box>
      )}

      <ChatInput
        onSend={sendMessage}
        disabled={loading}
      />
    </Drawer>
  );
};

export default ChatBot;