import { useEffect, useState } from "react";
import {
  Grid,
  CircularProgress,
  Alert,
  Typography,
  Box,
} from "@mui/material";
import { useNavigate } from "react-router-dom";

import PageContainer from "../../components/common/PageContainer";
import ApplicationCard, {
  ApplicationSummary,
} from "../../components/review/ApplicationCard";

const ReviewQueue = () => {
  const navigate = useNavigate();

  const [applications, setApplications] = useState<ApplicationSummary[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    loadApplications();
  }, []);

  const loadApplications = async () => {
    try {
      setLoading(true);

      const response = await fetch(
        "http://127.0.0.1:8000/api/review/"
      );

      if (!response.ok) {
        throw new Error("Unable to load review queue.");
      }

      const result = await response.json();

      console.log(result);

      setApplications(result);
    } catch (err) {
      console.error(err);
      setError("Unable to load application summary.");
    } finally {
      setLoading(false);
    }
  };

  const handleViewDetails = (application: string) => {
    navigate(`/review/${encodeURIComponent(application)}`);
  };

  if (loading) {
    return (
      <PageContainer title="Review Queue">
        <Box
          display="flex"
          justifyContent="center"
          mt={8}
        >
          <CircularProgress />
        </Box>
      </PageContainer>
    );
  }

  if (error) {
    return (
      <PageContainer title="Review Queue">
        <Alert severity="error">{error}</Alert>
      </PageContainer>
    );
  }

  return (
    <PageContainer title="Review Queue">
      <Typography
        variant="h5"
        sx={{
          fontWeight: 700,
          mb: 1,
        }}
      >
        Duplicate Accounts by Application
      </Typography>

      <Typography
        variant="body1"
        color="text.secondary"
        sx={{ mb: 4 }}
      >
        Select an application to review duplicate account recommendations
        generated by the AI engine.
      </Typography>

      <Grid container spacing={3}>
        {applications.map((app) => (
          <Grid
            key={app.application}
            size={{ xs: 12, sm: 6, md: 4, lg: 3 }}
          >
            <ApplicationCard
              application={app}
              onView={handleViewDetails}
            />
          </Grid>
        ))}
      </Grid>
    </PageContainer>
  );
};

export default ReviewQueue;